name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install black codespell flake8 isort mypy pytest pyupgrade safety
      - run: black --check . || true
      - run: codespell --quiet-level=2 --skip="*.txt" || true
      - run: flake8 . --count --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt || true  # There are in setup.py
      - run: pip install einops fire ftfy pytorch-pretrained-biggan regex torch torchvision tqdm
      - run: mypy --ignore-missing-imports . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
